### ISSUE TITLE
为什么我的output为空啊 初学不懂

### ISSUE THREAD

**Issue by QI-charles** [jannson/wordmaker#10]
<img width="432" alt="2017-02-12 12 45 58" src="https://cloud.githubusercontent.com/assets/6072224/22859716/3fbc6e18-f121-11e6-804e-083781ca2c1d.png">

**Comment by jannson** [comment]
文本用大一点的，还有要是 GBK 编码的。

**Comment by QI-charles** [comment]
解决了，文本太小了，谢谢。再请教一个问题，就是我这些刚提取出来的新生词怎么加入系统的或者自定义的字典中去啊？ 因为我想做一个特定领域问答系统，提取专业词汇比较关键，您有什么好的想法么？

**Comment by QI-charles** [comment]
@jannson 请问您的yaha分词有没有提取句子关键词的方法？

**Comment by jannson** [comment]
里面有一些 demo，网上也有很多不同的算法。你可以参考下这个项目：https://github.com/isnowfy/snownlp

要把新词加到 yaha 里面简单啊，就是把词与频率加进去。
