### ISSUE TITLE
Non-ISO extended-ASCII编码问题

### ISSUE THREAD

**Issue by Roottan** [jannson/wordmaker#11]
为什么用./bin/wordmaker input.txt output.txt  命令后产生的文件，在more 下显示正常但vi 就乱码，也不能进行转换。file output.txt 显示Non-ISO extended-ASCII编码问题， 求解决。ubuntu 系统

**Comment by charles0-0** [comment]
我的在MacOS 也是这种情况，求解决方法

**Comment by jannson** [comment]
本质原因是因为用了 GBK 编码，没有用 utf-8 编码导致的。需要你们用相关的工具把文件转成 utf-8 ，再用 vi 来查看。
要使用 utf-8 编码，软件实现更复杂，这个是为了给大家学习的项目，不打算实现过于复杂了。
